"use client";
import { useCallback, useEffect, useState } from "react";
import { Building2, Check, Copy, Power, PowerOff } from "lucide-react";

type Company = { id:string; name:string; hostname:string; adminTechId:string|null; active:boolean; technicianCount:number; qcCount:number };
type IssuedCompany = { name:string; hostname:string; adminTechId:string; pin:string; loginUrl:string };

export default function CompanySettings(){
 const [companies,setCompanies]=useState<Company[]>([]),[name,setName]=useState(""),[slug,setSlug]=useState(""),[hostname,setHostname]=useState(""),[adminTechId,setAdminTechId]=useState(""),[issued,setIssued]=useState<IssuedCompany|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[copied,setCopied]=useState(false);
 const load=useCallback(async(signal?:AbortSignal)=>{const response=await fetch("/api/companies",{cache:"no-store",signal});const result=await response.json() as {companies?:Company[];error?:string};if(!response.ok)throw Error(result.error||"Could not load companies.");if(!signal?.aborted)setCompanies(result.companies??[]);},[]);
 useEffect(()=>{const controller=new AbortController();void load(controller.signal).catch(cause=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:"Could not load companies.");});return()=>controller.abort();},[load]);
 function updateName(value:string){setName(value);if(!slug||slug===name.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,30))setSlug(value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,30));}
 async function addCompany(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");setNotice("");setIssued(null);setCopied(false);try{const response=await fetch("/api/companies",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,slug,hostname,adminTechId})});const result=await response.json() as {company?:IssuedCompany;error?:string};if(!response.ok||!result.company)throw Error(result.error||"Could not create the company.");setIssued(result.company);setName("");setSlug("");setHostname("");setAdminTechId("");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Could not create the company.");}finally{setBusy(false);}}
 async function setCompanyActive(company:Company,active:boolean){setBusy(true);setError("");setNotice("");try{const response=await fetch(`/api/companies/${encodeURIComponent(company.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active})});const result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error||"Could not update the company.");await load();setNotice(`${company.name} was ${active?"reactivated":"disabled"}. Its saved information was kept.`);}catch(cause){setError(cause instanceof Error?cause.message:"Could not update the company.");}finally{setBusy(false);}}
 async function copySetup(){if(!issued)return;try{await navigator.clipboard.writeText(`TQA Automatic Upload\nCompany: ${issued.name}\nLogin: ${issued.loginUrl}\nAdmin ID: ${issued.adminTechId}\nTemporary PIN: ${issued.pin}`);setCopied(true);}catch{setError("Could not copy the setup details. Copy them manually below.");}}
 return <div id="companies-settings"><section className="qc-pin-panel settings-panel"><div className="settings-section-title"><Building2 size={21}/><h2>Add company</h2></div><p>Create a separate company workspace and its first administrator after its domain points to this Coolify service.</p><form className="company-create-form" onSubmit={event=>void addCompany(event)}><label>Company name<input value={name} maxLength={80} placeholder="Example Cable Services" onChange={event=>updateName(event.target.value)} required/></label><label>Tenant ID<input value={slug} maxLength={30} placeholder="example-cable" pattern="[a-z0-9](?:[a-z0-9-]{0,28}[a-z0-9])?" onChange={event=>setSlug(event.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))} required/><small>Permanent internal ID</small></label><label>Company domain<input value={hostname} maxLength={253} placeholder="qc.example.com" onChange={event=>setHostname(event.target.value.toLowerCase().replace(/^https?:\/\//,"").split("/")[0])} required/><small>Domain only, without https://</small></label><label>Primary admin ID<input value={adminTechId} maxLength={32} placeholder="ADMIN01" onChange={event=>setAdminTechId(event.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,""))} required/></label><button className="button dark" disabled={busy}>{busy?"Creating…":"Create company"}</button></form>{issued&&<div className="issued-pin company-issued" role="status"><strong>{issued.name} is ready</strong><span className="company-login-link">{issued.loginUrl}</span><p>Admin ID: <b>{issued.adminTechId}</b> · Temporary PIN: <b>{issued.pin}</b></p><button type="button" className="button light" onClick={()=>void copySetup()}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?"Copied":"Copy setup details"}</button></div>}</section><section className="qc-pin-panel settings-panel"><div className="settings-section-title"><Building2 size={21}/><h2>Companies</h2></div><p>Disabling a company prevents all of its administrators and technicians from signing in. Its QCs and pictures remain stored.</p>{companies.length?<div className="qc-tech-rows">{companies.map(company=><div className="qc-tech-manage-row company-row" key={company.id}><div><strong>{company.name}</strong><small>{company.hostname} · Admin {company.adminTechId||"not assigned"}</small><span>{company.technicianCount} technicians · {company.qcCount} QCs · {company.active?"Active":"Disabled"}</span></div><div className="qc-tech-manage-actions">{company.active?<button type="button" className="button light qc-remove-button" disabled={busy} onClick={()=>void setCompanyActive(company,false)}><PowerOff size={16}/>Disable</button>:<button type="button" className="button light" disabled={busy} onClick={()=>void setCompanyActive(company,true)}><Power size={16}/>Reactivate</button>}</div></div>)}</div>:<p>No customer companies yet.</p>}</section>{notice&&<p className="qc-notice" role="status">{notice}</p>}{error&&<p className="form-error" role="alert">{error}</p>}</div>;
}
