import { env } from "@/lib/local-env";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { isPlatformOwner } from "@/app/access";
import { hashPin,newPin,normalizeTechId,randomHex,sameOrigin } from "@/lib/tech-auth";
import { encryptPin } from "@/lib/pin-vault";
export const dynamic="force-dynamic";
const slugPattern=/^[a-z0-9](?:[a-z0-9-]{0,28}[a-z0-9])?$/;const reserved=new Set(["admin","api","app","default","owner","qc","www"]);
const hostnamePattern=/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+(?:[a-z]{2,63}|localhost)$/;
function companyLoginUrl(request:Request,hostname:string){const url=new URL(request.url),forwarded=request.headers.get("x-forwarded-proto")?.split(",")[0]?.trim();return `${forwarded?`${forwarded}:`:url.protocol}//${hostname}${url.port?`:${url.port}`:""}/login`;}
export async function GET(){const user=await getChatGPTUser();if(!isPlatformOwner(user))return Response.json({error:"Only the platform owner can manage companies."},{status:403});try{const result=await env.DB.prepare(`SELECT t.id,t.name,t.active,d.hostname,(SELECT MIN(tech_id) FROM technicians WHERE tenant_id=t.id AND is_admin=1) AS adminTechId,(SELECT COUNT(*) FROM technicians WHERE tenant_id=t.id AND is_admin=0) AS technicianCount,(SELECT COUNT(*) FROM qc_submissions WHERE tenant_id=t.id) AS qcCount FROM tenants t JOIN tenant_domains d ON d.tenant_id=t.id WHERE t.id<>'default' GROUP BY t.id ORDER BY t.active DESC,t.name COLLATE NOCASE`).all<{id:string;name:string;active:number;hostname:string;adminTechId:string|null;technicianCount:number;qcCount:number}>();return Response.json({companies:result.results.map(company=>({...company,active:company.active===1}))},{headers:{"Cache-Control":"private, no-store"}});}catch(error){console.error("Company list failed",error);return Response.json({error:"Could not load companies."},{status:503});}}
export async function POST(request:Request){if(!sameOrigin(request))return Response.json({error:"Invalid request origin."},{status:403});const user=await getChatGPTUser();if(!isPlatformOwner(user))return Response.json({error:"Only the platform owner can add companies."},{status:403});const body=await request.json().catch(()=>null) as {name?:unknown;slug?:unknown;hostname?:unknown;adminTechId?:unknown}|null;const name=typeof body?.name==="string"?body.name.trim().replace(/\s+/g," "):"",slug=typeof body?.slug==="string"?body.slug.trim().toLowerCase():"",hostname=typeof body?.hostname==="string"?body.hostname.trim().toLowerCase().replace(/\.$/,""):"",adminTechId=normalizeTechId(body?.adminTechId);if(name.length<2||name.length>80)return Response.json({error:"Enter a company name between 2 and 80 characters."},{status:400});if(!slugPattern.test(slug)||reserved.has(slug))return Response.json({error:"Enter a unique tenant ID using letters, numbers, and hyphens."},{status:400});if(!hostnamePattern.test(hostname))return Response.json({error:"Enter the complete domain assigned to this company."},{status:400});if(!adminTechId)return Response.json({error:"Enter a valid primary admin ID."},{status:400});const now=Date.now();try{const existing=await env.DB.prepare("SELECT id FROM tenants WHERE id=? UNION SELECT tenant_id AS id FROM tenant_domains WHERE hostname=?").bind(slug,hostname).first();if(existing)return Response.json({error:"That tenant ID or domain is already in use."},{status:409});const pin=newPin(),salt=randomHex(16);const[hash,pinCiphertext]=await Promise.all([hashPin(pin,salt),encryptPin(pin,env.PIN_ENCRYPTION_KEY)]);await env.DB.batch([env.DB.prepare("INSERT INTO tenants(id,name,active,created_at) VALUES(?,?,1,?)").bind(slug,name,now),env.DB.prepare("INSERT INTO tenant_domains(hostname,tenant_id,created_at) VALUES(?,?,?)").bind(hostname,slug,now),env.DB.prepare("INSERT INTO technicians(tenant_id,tech_id,pin_salt,pin_hash,pin_ciphertext,active,is_admin,failed_attempts,locked_until,created_at) VALUES(?,?,?,?,?,1,1,0,0,?)").bind(slug,adminTechId,salt,hash,pinCiphertext,now)]);return Response.json({company:{id:slug,name,hostname,adminTechId,pin,loginUrl:companyLoginUrl(request,hostname)}},{status:201,headers:{"Cache-Control":"no-store"}});}catch(error){console.error("Company creation failed",error);return Response.json({error:"Could not create the company. Try a different tenant ID, domain, or admin ID."},{status:503});}}
